Description of gmmbvl_em_init_km
Home > gmmbayestb-v1.0 > gmmbvl_em_init_km.m
gmmbvl_em_init_km
PURPOSE
gmmbvl_em_init_km - initialization of EM for Gaussian mixtures
SYNOPSIS
function [W,M,R,P,sigma] = gmmbvl_em_init_km(X,k,dyn)
DESCRIPTION
gmmbvl_em_init_km - initialization of EM for Gaussian mixtures
[W,M,R,P,sigma] = gmmbvl_em_init_km(X,k,dyn)
  X - (n x d) matrix of input data
  k - initial number of Gaussian components
  dyn - if 1 then perform dynamic component allocation else normal EM
returns
  W - (k x 1) vector of mixing weights
  M - (k x d) matrix of components means
  R - (k x d^2) matrix of Cholesky submatrices of components covariances
  P - (n x k) the posteriors to be used in EM step after initialization
  of priors, means, and components covariance matrices
CROSS-REFERENCE INFORMATION
This function calls:
gmmbvl_em_gauss gmmbvl_em_gauss - compute likelihoods for all points and all components
gmmbvl_kmeans gmmbvl_kmeans - clustering with k-means (or Generalized Lloyd or LBG) algorithm
gmmbvl_sqdist gmmbvl_sqdist - computes pairwise squared Euclidean distances between points
This function is called by:
gmmbvl_em gmmbvl_em - EM algorithm for adaptive multivariate Gaussian mixtures
SOURCE CODE
function [W,M,R,P,sigma] = gmmbvl_em_init_km(X,k,dyn)
%gmmbvl_em_init_km - initialization of EM for Gaussian mixtures
%
%[W,M,R,P,sigma] = gmmbvl_em_init_km(X,k,dyn)
%  X - (n x d) matrix of input data
%  k - initial number of Gaussian components
%  dyn - if 1 then perform dynamic component allocation else normal EM
%returns
%  W - (k x 1) vector of mixing weights
%  M - (k x d) matrix of components means
%  R - (k x d^2) matrix of Cholesky submatrices of components covariances
%  P - (n x k) the posteriors to be used in EM step after initialization
%  of priors, means, and components covariance matrices
% Nikos Vlassis & Sjaak Verbeek 2002
%
% $Name:  $
[n,d] = size(X);
[tmp,M,tmp2] = gmmbvl_kmeans(X,[],k,0,0,0,0);
[D,I]        = min(gmmbvl_sqdist(M',X'),[],1);
% mixing weights
W = zeros(k,1);
for i=1:k
    W(i) = length(find(I==i))/n;
end
% covariance matrices
R = zeros(k,d^2);
if k > 1
    for j = 1:k
        J = find(I==j);
        if length(J)>2*d;
            Sj = cov(X(J,:));
        else
            Sj = cov(X);
        end
        Rj = chol(Sj);
        R(j,:) = Rj(:)';
    end
else
    S = cov(X);
    R = chol(S);
    R = R(:)';
end
% compute likelihoods L (n x k)
L = gmmbvl_em_gauss(X,M,R);
% compute mixture likelihoods F (n x 1)
F = L * W;
F(find(F < eps)) = eps;
% compute posteriors P (n x k)
P = L .* repmat(W',n,1)  ./ repmat(F,1,k);
sigma = 0.5 * (4/(d+2)/n)^(1/(d+4)) * sqrt(norm(cov(X)));