Description of gmmbvl_sqdist
Home > gmmbayestb-v1.0 > gmmbvl_sqdist.m
gmmbvl_sqdist
PURPOSE
gmmbvl_sqdist - computes pairwise squared Euclidean distances between points
SYNOPSIS
function d = gmmbvl_sqdist(a,b)
DESCRIPTION
 gmmbvl_sqdist - computes pairwise squared Euclidean distances between points
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
gmmbvl_em_init_km gmmbvl_em_init_km - initialization of EM for Gaussian mixtures
gmmbvl_kmeans gmmbvl_kmeans - clustering with k-means (or Generalized Lloyd or LBG) algorithm
gmmbvl_rand_split
SOURCE CODE
function d = gmmbvl_sqdist(a,b)
% gmmbvl_sqdist - computes pairwise squared Euclidean distances between points
% original version by Roland Bunschoten, 1999
%
% $Name:  $
if size(a,1)==1
  d = repmat(a',1,length(b)) - repmat(b,length(a),1);
  d = d.^2;
else
  aa = sum(a.*a); bb = sum(b.*b); ab = a'*b;
  d = abs(repmat(aa',[1 size(bb,2)]) + repmat(bb,[size(aa,2) 1]) - 2*ab);
end