Description of warning_wrap
Home > gmmbayestb-v1.0 > warning_wrap.m
warning_wrap
PURPOSE
WARNING_WRAP() warning function wrapper
SYNOPSIS
function [] = warning_wrap(varargin);
DESCRIPTION
 WARNING_WRAP()  warning function wrapper
 to allow Matlab R13 style warning calls in Matlab R12
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
getargs GETARGS parse variable argument list into a struct
gmmb_covfixer GMMB_COVFIXER - force matrix to be a valid covariance matrix
gmmb_em GMMB_EM - EM estimated GMM parameters
gmmb_fj GMMB_FJ - Figueiredo-Jain estimated GMM parameters
gmmb_gem GMMB_GEM - Greedy EM estimated GMM parameters
SOURCE CODE
% WARNING_WRAP()  warning function wrapper
% to allow Matlab R13 style warning calls in Matlab R12
% $Name:  $
% $Id: warning_wrap.m,v 1.1 2004/11/02 08:32:22 paalanen Exp $
% Pekka Paalanen, 2004
function [] = warning_wrap(varargin);
old_version = strcmp(version('-release'), '12');
if old_version
    if nargin > 1
        warning(varargin{2});
    else
        warning(varargin{1});
    end
else
    % Assume version Matlab R13
    warning(varargin{:});
end